services:
  app:
    build: .
    container_name: app
    ports:
      - "3001:3001"
    # depends_on:
    #   - db
    # env_file:
    #   - .env

  # db:
  #   image: postgres:latest
  #   container_name: postgres_container
  #   environment:
  #     POSTGRES_DB: bussinessbot
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: secret
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: